// <auto-generated />
using System;
using System.Collections.Generic;
using Bastion.Organizacion.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bastion.Organizacion.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizacionDbContext))]
    [Migration("20260902175913_MaestrosDelSeptimoApartado")]
    partial class MaestrosDelSeptimoApartado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organizacion")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Auditoria.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cambio")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cambio");

                    b.Property<Guid>("CorrelacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlacion_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Valores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("valores");

                    b.HasKey("Id")
                        .HasName("pk_registros");

                    b.HasIndex("CorrelacionId")
                        .HasDatabaseName("ix_registros_correlacion_id");

                    b.HasIndex("OcurridoEn")
                        .HasDatabaseName("ix_registros_ocurrido_en");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_registros_entidad_entidad_id");

                    b.ToTable("registros", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_registros_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la traza; auditarla sería recursión, no información");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoDeLaBandeja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cuerpo");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<DateTimeOffset?>("PublicadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id")
                        .HasName("pk_bandeja_de_salida");

                    b.HasIndex("EventoId")
                        .IsUnique()
                        .HasDatabaseName("ix_bandeja_evento_id");

                    b.HasIndex("Estado", "Id")
                        .HasDatabaseName("ix_bandeja_de_salida_estado_id");

                    b.ToTable("bandeja_de_salida", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_bandeja_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la cola de eventos; publicarlos es fontanería, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("Consumidor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("consumidor");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.HasKey("EventoId", "Consumidor")
                        .HasName("pk_eventos_procesados");

                    b.ToTable("eventos_procesados", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la huella de que un consumidor ya pasó; no es un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Idempotencia.RegistroDeIdempotencia", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Metodo")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("metodo");

                    b.Property<string>("Ruta")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ruta");

                    b.Property<string>("Clave")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("clave");

                    b.Property<int?>("CodigoDeEstado")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_de_estado");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("TipoDeContenido")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tipo_de_contenido");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ubicacion");

                    b.HasKey("EmpresaId", "UsuarioId", "Metodo", "Ruta", "Clave")
                        .HasName("pk_claves_de_idempotencia");

                    b.ToTable("claves_de_idempotencia", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es el recibo de una petición ya atendida, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Bloqueo", "Bastion.Organizacion.Domain.Almacenes.Almacen.Bloqueo#Bloqueo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("Desde")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("bloqueado_en")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<bool>("EstaBloqueado")
                                .HasColumnType("boolean")
                                .HasColumnName("bloqueado")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Motivo")
                                .HasColumnType("text")
                                .HasColumnName("motivo_del_bloqueo")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Direccion", "Bastion.Organizacion.Domain.Almacenes.Almacen.Direccion#Direccion", b1 =>
                        {
                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(70)
                                .HasColumnType("character varying(70)")
                                .HasColumnName("direccion_calle")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("direccion_codigo_postal")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Numero")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("direccion_numero")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("direccion_pais")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Poblacion")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("direccion_poblacion")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Subdivision")
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("direccion_subdivision")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");
                        });

                    b.HasKey("Id")
                        .HasName("pk_almacenes");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_almacenes_empresa_id_codigo");

                    b.ToTable("almacenes", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Divisas.Divisa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_divisas");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_divisas_codigo");

                    b.ToTable("divisas", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Divisas.TipoCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("DivisaDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("divisa_destino_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("DivisaOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("divisa_origen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<decimal>("Tasa")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("tasa")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_tipos_de_cambio");

                    b.HasIndex("DivisaDestinoId")
                        .HasDatabaseName("ix_tipos_de_cambio_divisa_destino_id");

                    b.HasIndex("DivisaOrigenId", "DivisaDestinoId", "Fecha")
                        .IsUnique()
                        .HasDatabaseName("ix_tipos_de_cambio_divisa_origen_id_divisa_destino_id_fecha");

                    b.ToTable("tipos_de_cambio", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Ejercicios.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("FechaDeFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_fin")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("FechaDeInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_inicio")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_ejercicios");

                    b.HasIndex("EmpresaId", "Anio")
                        .IsUnique()
                        .HasDatabaseName("ix_ejercicios_empresa_id_anio");

                    b.ToTable("ejercicios", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("DivisaBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("divisa_base")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("nif")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("RegimenDeIva")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regimen_de_iva")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Bloqueo", "Bastion.Organizacion.Domain.Empresas.Empresa.Bloqueo#Bloqueo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("Desde")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("bloqueado_en")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<bool>("EstaBloqueado")
                                .HasColumnType("boolean")
                                .HasColumnName("bloqueado")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Motivo")
                                .HasColumnType("text")
                                .HasColumnName("motivo_del_bloqueo")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DomicilioFiscal", "Bastion.Organizacion.Domain.Empresas.Empresa.DomicilioFiscal#Direccion", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(70)
                                .HasColumnType("character varying(70)")
                                .HasColumnName("domicilio_fiscal_calle")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("domicilio_fiscal_codigo_postal")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Numero")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("domicilio_fiscal_numero")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("domicilio_fiscal_pais")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Poblacion")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("domicilio_fiscal_poblacion")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Subdivision")
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("domicilio_fiscal_subdivision")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");
                        });

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Nif")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_nif");

                    b.ToTable("empresas", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Impuestos.Impuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("CuentaRepercutido")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cuenta_repercutido")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("CuentaSoportado")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cuenta_soportado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigente_desde")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigente_hasta")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.HasKey("Id")
                        .HasName("pk_impuestos");

                    b.HasIndex("Codigo", "VigenteDesde")
                        .HasDatabaseName("ix_impuestos_codigo_vigente_desde");

                    b.ToTable("impuestos", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Series.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<long>("Contador")
                        .HasColumnType("bigint")
                        .HasColumnName("contador")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejercicio_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formato")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_documento")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("EjercicioId")
                        .HasDatabaseName("ix_series_ejercicio_id");

                    b.HasIndex("EmpresaId", "EjercicioId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_series_empresa_id_ejercicio_id_codigo");

                    b.ToTable("series", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Ubicaciones.Ubicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descripcion")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estante")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estante")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Hueco")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hueco")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Pasillo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("pasillo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Bloqueo", "Bastion.Organizacion.Domain.Ubicaciones.Ubicacion.Bloqueo#Bloqueo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("Desde")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("bloqueado_en")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<bool>("EstaBloqueado")
                                .HasColumnType("boolean")
                                .HasColumnName("bloqueado")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Motivo")
                                .HasColumnType("text")
                                .HasColumnName("motivo_del_bloqueo")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");
                        });

                    b.HasKey("Id")
                        .HasName("pk_ubicaciones");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_ubicaciones_empresa_id");

                    b.HasIndex("AlmacenId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_ubicaciones_almacen_id_codigo");

                    b.ToTable("ubicaciones", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Unidades.ConversionUM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal>("Factor")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("factor")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<Guid>("UnidadDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_destino_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UnidadOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_origen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_conversiones_de_unidades");

                    b.HasIndex("UnidadDestinoId")
                        .HasDatabaseName("ix_conversiones_de_unidades_unidad_destino_id");

                    b.HasIndex("UnidadOrigenId", "UnidadDestinoId")
                        .IsUnique()
                        .HasDatabaseName("ix_conversiones_de_unidades_unidad_origen_id_unidad_destino_id");

                    b.ToTable("conversiones_de_unidades", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Unidades.UnidadMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<int>("Decimales")
                        .HasColumnType("integer")
                        .HasColumnName("decimales")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nombre")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_unidades_de_medida");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_unidades_de_medida_codigo");

                    b.ToTable("unidades_de_medida", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Almacenes.Almacen", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_almacenes_empresas_empresa_id");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Divisas.TipoCambio", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Divisas.Divisa", null)
                        .WithMany()
                        .HasForeignKey("DivisaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tipos_de_cambio_divisas_divisa_destino_id");

                    b.HasOne("Bastion.Organizacion.Domain.Divisas.Divisa", null)
                        .WithMany()
                        .HasForeignKey("DivisaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tipos_de_cambio_divisas_divisa_origen_id");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Ejercicios.Ejercicio", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ejercicios_empresas_empresa_id");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Series.Serie", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Ejercicios.Ejercicio", null)
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_ejercicios_ejercicio_id");

                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_empresas_empresa_id");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Ubicaciones.Ubicacion", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Almacenes.Almacen", null)
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ubicaciones_almacenes_almacen_id");

                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ubicaciones_empresas_empresa_id");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Unidades.ConversionUM", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Unidades.UnidadMedida", null)
                        .WithMany()
                        .HasForeignKey("UnidadDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversiones_de_unidades_unidades_de_medida_unidad_destino_");

                    b.HasOne("Bastion.Organizacion.Domain.Unidades.UnidadMedida", null)
                        .WithMany()
                        .HasForeignKey("UnidadOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_conversiones_de_unidades_unidades_de_medida_unidad_origen_id");
                });
#pragma warning restore 612, 618
        }
    }
}
