// <auto-generated />
using System;
using System.Collections.Generic;
using Bastion.Identidad.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bastion.Identidad.Infrastructure.Migrations
{
    [DbContext(typeof(IdentidadDbContext))]
    partial class IdentidadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identidad")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Auditoria.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cambio")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cambio");

                    b.Property<Guid>("CorrelacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlacion_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Valores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("valores");

                    b.HasKey("Id")
                        .HasName("pk_registros");

                    b.HasIndex("CorrelacionId")
                        .HasDatabaseName("ix_registros_correlacion_id");

                    b.HasIndex("OcurridoEn")
                        .HasDatabaseName("ix_registros_ocurrido_en");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_registros_entidad_entidad_id");

                    b.ToTable("registros", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_registros_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la traza; auditarla sería recursión, no información");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoDeLaBandeja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cuerpo");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<DateTimeOffset?>("PublicadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id")
                        .HasName("pk_bandeja_de_salida");

                    b.HasIndex("EventoId")
                        .IsUnique()
                        .HasDatabaseName("ix_bandeja_evento_id");

                    b.HasIndex("Estado", "Id")
                        .HasDatabaseName("ix_bandeja_de_salida_estado_id");

                    b.ToTable("bandeja_de_salida", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_bandeja_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la cola de eventos; publicarlos es fontanería, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("Consumidor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("consumidor");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.HasKey("EventoId", "Consumidor")
                        .HasName("pk_eventos_procesados");

                    b.ToTable("eventos_procesados", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la huella de que un consumidor ya pasó; no es un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Idempotencia.RegistroDeIdempotencia", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Metodo")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("metodo");

                    b.Property<string>("Ruta")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ruta");

                    b.Property<string>("Clave")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("clave");

                    b.Property<int?>("CodigoDeEstado")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_de_estado");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("TipoDeContenido")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tipo_de_contenido");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ubicacion");

                    b.HasKey("EmpresaId", "UsuarioId", "Metodo", "Ruta", "Clave")
                        .HasName("pk_claves_de_idempotencia");

                    b.ToTable("claves_de_idempotencia", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es el recibo de una petición ya atendida, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Roles.PermisoDeRol", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<string>("Permiso")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("permiso");

                    b.HasKey("RolId", "Permiso")
                        .HasName("pk_permisos_de_rol");

                    b.ToTable("permisos_de_rol", "identidad");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Roles.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<bool>("EsDelSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("es_del_sistema")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_codigo");

                    b.ToTable("roles", "identidad");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Sesiones.TokenDeRefresco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CanjeadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canjeado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaActivaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_activa_id");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<Guid?>("SustituidoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sustituido_por_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_tokens_de_refresco");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_tokens_de_refresco_familia_id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_tokens_de_refresco_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_tokens_de_refresco_usuario_id");

                    b.ToTable("tokens_de_refresco", "identidad");

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|emision de refresco: rota cada quince minutos y lleva un resumen de credencial. El acceso deja traza en Usuario.UltimoAccesoEn, que es el dato que interesa.");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Membresia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.HasKey("Id")
                        .HasName("pk_membresias");

                    b.HasIndex("UsuarioId", "EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ix_membresias_usuario_id_empresa_id");

                    b.ToTable("membresias", "identidad");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.RolDeMembresia", b =>
                {
                    b.Property<Guid>("MembresiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("membresia_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("MembresiaId", "RolId")
                        .HasName("pk_roles_de_membresia");

                    b.ToTable("roles_de_membresia", "identidad");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("HashDeContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_de_contrasena")
                        .HasAnnotation("Bastion:Auditoria", "Secreta|resumen de credencial: el historial de resumenes es un boton de ataque");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos_fallidos")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset?>("RechazadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rechazado_hasta")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Bloqueo", "Bastion.Identidad.Domain.Usuarios.Usuario.Bloqueo#Bloqueo", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset?>("Desde")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("bloqueado_en")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<bool>("EstaBloqueado")
                                .HasColumnType("boolean")
                                .HasColumnName("bloqueado")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Motivo")
                                .HasColumnType("text")
                                .HasColumnName("motivo_del_bloqueo")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");
                        });

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo");

                    b.ToTable("usuarios", "identidad");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Roles.PermisoDeRol", b =>
                {
                    b.HasOne("Bastion.Identidad.Domain.Roles.Rol", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permisos_de_rol_roles_rol_id");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Sesiones.TokenDeRefresco", b =>
                {
                    b.HasOne("Bastion.Identidad.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_de_refresco_usuarios_usuario_id");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Membresia", b =>
                {
                    b.HasOne("Bastion.Identidad.Domain.Usuarios.Usuario", null)
                        .WithMany("Membresias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membresias_usuarios_usuario_id");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.RolDeMembresia", b =>
                {
                    b.HasOne("Bastion.Identidad.Domain.Usuarios.Membresia", null)
                        .WithMany("Roles")
                        .HasForeignKey("MembresiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_de_membresia_membresias_membresia_id");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Roles.Rol", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Membresia", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("Membresias");
                });
#pragma warning restore 612, 618
        }
    }
}
