// <auto-generated />
using System;
using Bastion.Identidad.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bastion.Identidad.Infrastructure.Migrations
{
    [DbContext(typeof(IdentidadDbContext))]
    partial class IdentidadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identidad")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bastion.Identidad.Domain.Roles.PermisoDeRol", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.Property<string>("Permiso")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("permiso");

                    b.HasKey("RolId", "Permiso")
                        .HasName("pk_permisos_de_rol");

                    b.ToTable("permisos_de_rol", "identidad");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Roles.Rol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<bool>("EsDelSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("es_del_sistema");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_codigo");

                    b.ToTable("roles", "identidad");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Sesiones.TokenDeRefresco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CanjeadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("canjeado_en");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("EmpresaActivaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_activa_id");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<Guid>("FamiliaId")
                        .HasColumnType("uuid")
                        .HasColumnName("familia_id");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<string>("Motivo")
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<DateTimeOffset?>("RevocadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revocado_en");

                    b.Property<Guid?>("SustituidoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sustituido_por_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_tokens_de_refresco");

                    b.HasIndex("FamiliaId")
                        .HasDatabaseName("ix_tokens_de_refresco_familia_id");

                    b.HasIndex("Hash")
                        .IsUnique()
                        .HasDatabaseName("ix_tokens_de_refresco_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_tokens_de_refresco_usuario_id");

                    b.ToTable("tokens_de_refresco", "identidad");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Membresia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_membresias");

                    b.HasIndex("UsuarioId", "EmpresaId")
                        .IsUnique()
                        .HasDatabaseName("ix_membresias_usuario_id_empresa_id");

                    b.ToTable("membresias", "identidad");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.RolDeMembresia", b =>
                {
                    b.Property<Guid>("MembresiaId")
                        .HasColumnType("uuid")
                        .HasColumnName("membresia_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("MembresiaId", "RolId")
                        .HasName("pk_roles_de_membresia");

                    b.ToTable("roles_de_membresia", "identidad");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BloqueadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_en");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("correo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("HashDeContrasena")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hash_de_contrasena");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset?>("RechazadoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rechazado_hasta");

                    b.Property<DateTimeOffset?>("UltimoAccesoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso_en");

                    b.HasKey("Id")
                        .HasName("pk_usuarios");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_correo");

                    b.ToTable("usuarios", "identidad");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Roles.PermisoDeRol", b =>
                {
                    b.HasOne("Bastion.Identidad.Domain.Roles.Rol", null)
                        .WithMany("Permisos")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permisos_de_rol_roles_rol_id");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Sesiones.TokenDeRefresco", b =>
                {
                    b.HasOne("Bastion.Identidad.Domain.Usuarios.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tokens_de_refresco_usuarios_usuario_id");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Membresia", b =>
                {
                    b.HasOne("Bastion.Identidad.Domain.Usuarios.Usuario", null)
                        .WithMany("Membresias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membresias_usuarios_usuario_id");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.RolDeMembresia", b =>
                {
                    b.HasOne("Bastion.Identidad.Domain.Usuarios.Membresia", null)
                        .WithMany("Roles")
                        .HasForeignKey("MembresiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_de_membresia_membresias_membresia_id");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Roles.Rol", b =>
                {
                    b.Navigation("Permisos");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Membresia", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Bastion.Identidad.Domain.Usuarios.Usuario", b =>
                {
                    b.Navigation("Membresias");
                });
#pragma warning restore 612, 618
        }
    }
}
