// <auto-generated />
using System;
using Bastion.Organizacion.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bastion.Organizacion.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizacionDbContext))]
    partial class OrganizacionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organizacion")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bastion.Organizacion.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BloqueadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_en");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_almacenes");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_almacenes_empresa_id_codigo");

                    b.ToTable("almacenes", "organizacion");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Ejercicios.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaDeFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_fin");

                    b.Property<DateOnly>("FechaDeInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_inicio");

                    b.HasKey("Id")
                        .HasName("pk_ejercicios");

                    b.HasIndex("EmpresaId", "Anio")
                        .IsUnique()
                        .HasDatabaseName("ix_ejercicios_empresa_id_anio");

                    b.ToTable("ejercicios", "organizacion");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BloqueadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueada_en");

                    b.Property<string>("DivisaBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("divisa_base");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("nif");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social");

                    b.Property<string>("RegimenDeIva")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regimen_de_iva");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Nif")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_nif");

                    b.ToTable("empresas", "organizacion");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Series.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<long>("Contador")
                        .HasColumnType("bigint")
                        .HasColumnName("contador");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejercicio_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formato");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_documento");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("EjercicioId")
                        .HasDatabaseName("ix_series_ejercicio_id");

                    b.HasIndex("EmpresaId", "EjercicioId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_series_empresa_id_ejercicio_id_codigo");

                    b.ToTable("series", "organizacion");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Almacenes.Almacen", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_almacenes_empresas_empresa_id");

                    b.OwnsOne("Bastion.BuildingBlocks.Domain.Direcciones.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("AlmacenId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(70)
                                .HasColumnType("character varying(70)")
                                .HasColumnName("direccion_calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("direccion_codigo_postal");

                            b1.Property<string>("Numero")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("direccion_numero");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("direccion_pais");

                            b1.Property<string>("Poblacion")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("direccion_poblacion");

                            b1.Property<string>("Subdivision")
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("direccion_subdivision");

                            b1.HasKey("AlmacenId");

                            b1.ToTable("almacenes", "organizacion");

                            b1.WithOwner()
                                .HasForeignKey("AlmacenId")
                                .HasConstraintName("fk_almacenes_almacenes_id");
                        });

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Ejercicios.Ejercicio", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ejercicios_empresas_empresa_id");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Empresas.Empresa", b =>
                {
                    b.OwnsOne("Bastion.BuildingBlocks.Domain.Direcciones.Direccion", "DomicilioFiscal", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(70)
                                .HasColumnType("character varying(70)")
                                .HasColumnName("domicilio_fiscal_calle");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("domicilio_fiscal_codigo_postal");

                            b1.Property<string>("Numero")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("domicilio_fiscal_numero");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("domicilio_fiscal_pais");

                            b1.Property<string>("Poblacion")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("domicilio_fiscal_poblacion");

                            b1.Property<string>("Subdivision")
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("domicilio_fiscal_subdivision");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("empresas", "organizacion");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId")
                                .HasConstraintName("fk_empresas_empresas_id");
                        });

                    b.Navigation("DomicilioFiscal")
                        .IsRequired();
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Series.Serie", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Ejercicios.Ejercicio", null)
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_ejercicios_ejercicio_id");

                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_empresas_empresa_id");
                });
#pragma warning restore 612, 618
        }
    }
}
