// <auto-generated />
using System;
using Bastion.Organizacion.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bastion.Organizacion.Infrastructure.Migrations
{
    [DbContext(typeof(OrganizacionDbContext))]
    partial class OrganizacionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("organizacion")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Auditoria.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cambio")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cambio");

                    b.Property<Guid>("CorrelacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlacion_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Valores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("valores");

                    b.HasKey("Id")
                        .HasName("pk_registros");

                    b.HasIndex("CorrelacionId")
                        .HasDatabaseName("ix_registros_correlacion_id");

                    b.HasIndex("OcurridoEn")
                        .HasDatabaseName("ix_registros_ocurrido_en");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_registros_entidad_entidad_id");

                    b.ToTable("registros", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_registros_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la traza; auditarla sería recursión, no información");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoDeLaBandeja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cuerpo");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<DateTimeOffset?>("PublicadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id")
                        .HasName("pk_bandeja_de_salida");

                    b.HasIndex("EventoId")
                        .IsUnique()
                        .HasDatabaseName("ix_bandeja_evento_id");

                    b.HasIndex("Estado", "Id")
                        .HasDatabaseName("ix_bandeja_de_salida_estado_id");

                    b.ToTable("bandeja_de_salida", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_bandeja_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la cola de eventos; publicarlos es fontanería, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("Consumidor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("consumidor");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.HasKey("EventoId", "Consumidor")
                        .HasName("pk_eventos_procesados");

                    b.ToTable("eventos_procesados", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la huella de que un consumidor ya pasó; no es un cambio de datos");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BloqueadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_almacenes");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_almacenes_empresa_id_codigo");

                    b.ToTable("almacenes", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Ejercicios.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("FechaDeFin")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_fin")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("FechaDeInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_inicio")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_ejercicios");

                    b.HasIndex("EmpresaId", "Anio")
                        .IsUnique()
                        .HasDatabaseName("ix_ejercicios_empresa_id_anio");

                    b.ToTable("ejercicios", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Empresas.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BloqueadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bloqueada_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("DivisaBase")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("divisa_base")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Nif")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("nif")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("razon_social")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("RegimenDeIva")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("regimen_de_iva")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_empresas");

                    b.HasIndex("Nif")
                        .IsUnique()
                        .HasDatabaseName("ix_empresas_nif");

                    b.ToTable("empresas", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Series.Serie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<long>("Contador")
                        .HasColumnType("bigint")
                        .HasColumnName("contador")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejercicio_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("formato")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_de_documento")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_series");

                    b.HasIndex("EjercicioId")
                        .HasDatabaseName("ix_series_ejercicio_id");

                    b.HasIndex("EmpresaId", "EjercicioId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_series_empresa_id_ejercicio_id_codigo");

                    b.ToTable("series", "organizacion");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Almacenes.Almacen", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_almacenes_empresas_empresa_id");

                    b.OwnsOne("Bastion.BuildingBlocks.Domain.Direcciones.Direccion", "Direccion", b1 =>
                        {
                            b1.Property<Guid>("AlmacenId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(70)
                                .HasColumnType("character varying(70)")
                                .HasColumnName("direccion_calle")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("direccion_codigo_postal")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Numero")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("direccion_numero")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("direccion_pais")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Poblacion")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("direccion_poblacion")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Subdivision")
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("direccion_subdivision")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.HasKey("AlmacenId");

                            b1.ToTable("almacenes", "organizacion");

                            b1.WithOwner()
                                .HasForeignKey("AlmacenId")
                                .HasConstraintName("fk_almacenes_almacenes_id");
                        });

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Ejercicios.Ejercicio", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ejercicios_empresas_empresa_id");
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Empresas.Empresa", b =>
                {
                    b.OwnsOne("Bastion.BuildingBlocks.Domain.Direcciones.Direccion", "DomicilioFiscal", b1 =>
                        {
                            b1.Property<Guid>("EmpresaId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasMaxLength(70)
                                .HasColumnType("character varying(70)")
                                .HasColumnName("domicilio_fiscal_calle")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("CodigoPostal")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("domicilio_fiscal_codigo_postal")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Numero")
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("domicilio_fiscal_numero")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("domicilio_fiscal_pais")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Poblacion")
                                .IsRequired()
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("domicilio_fiscal_poblacion")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Subdivision")
                                .HasMaxLength(35)
                                .HasColumnType("character varying(35)")
                                .HasColumnName("domicilio_fiscal_subdivision")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.HasKey("EmpresaId");

                            b1.ToTable("empresas", "organizacion");

                            b1.WithOwner()
                                .HasForeignKey("EmpresaId")
                                .HasConstraintName("fk_empresas_empresas_id");
                        });

                    b.Navigation("DomicilioFiscal")
                        .IsRequired();
                });

            modelBuilder.Entity("Bastion.Organizacion.Domain.Series.Serie", b =>
                {
                    b.HasOne("Bastion.Organizacion.Domain.Ejercicios.Ejercicio", null)
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_ejercicios_ejercicio_id");

                    b.HasOne("Bastion.Organizacion.Domain.Empresas.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_series_empresas_empresa_id");
                });
#pragma warning restore 612, 618
        }
    }
}
