// <auto-generated />
using System;
using System.Collections.Generic;
using Bastion.Inventario.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bastion.Inventario.Infrastructure.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20260919153044_ElAjusteLlevaSerieYNumero")]
    partial class ElAjusteLlevaSerieYNumero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventario")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Auditoria.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cambio")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cambio");

                    b.Property<Guid>("CorrelacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlacion_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Valores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("valores");

                    b.HasKey("Id")
                        .HasName("pk_registros");

                    b.HasIndex("CorrelacionId")
                        .HasDatabaseName("ix_registros_correlacion_id");

                    b.HasIndex("OcurridoEn")
                        .HasDatabaseName("ix_registros_ocurrido_en");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_registros_entidad_entidad_id");

                    b.ToTable("registros", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_registros_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la traza; auditarla sería recursión, no información");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoDeLaBandeja", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cuerpo");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<DateTimeOffset?>("PublicadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id")
                        .HasName("pk_bandeja_de_salida");

                    b.HasIndex("EventoId")
                        .IsUnique()
                        .HasDatabaseName("ix_bandeja_evento_id");

                    b.HasIndex("Estado", "Id")
                        .HasDatabaseName("ix_bandeja_de_salida_estado_id");

                    b.ToTable("bandeja_de_salida", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_bandeja_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la cola de eventos; publicarlos es fontanería, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("Consumidor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("consumidor");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.HasKey("EventoId", "Consumidor")
                        .HasName("pk_eventos_procesados");

                    b.ToTable("eventos_procesados", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la huella de que un consumidor ya pasó; no es un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Idempotencia.RegistroDeIdempotencia", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Metodo")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("metodo");

                    b.Property<string>("Ruta")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ruta");

                    b.Property<string>("Clave")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CaducaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("caduca_en");

                    b.Property<int?>("CodigoDeEstado")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_de_estado");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("TipoDeContenido")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tipo_de_contenido");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ubicacion");

                    b.HasKey("EmpresaId", "UsuarioId", "Metodo", "Ruta", "Clave")
                        .HasName("pk_claves_de_idempotencia");

                    b.HasIndex("CaducaEn")
                        .HasDatabaseName("ix_claves_de_idempotencia_caduca_en");

                    b.ToTable("claves_de_idempotencia", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es el recibo de una petición ya atendida, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Ajustes.Ajuste", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("FechaDeOperacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_operacion")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<long?>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid")
                        .HasColumnName("serie_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_ajustes");

                    b.HasIndex("EmpresaId", "FechaDeOperacion")
                        .HasDatabaseName("ix_ajustes_empresa_id_fecha_de_operacion");

                    b.HasIndex("SerieId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_ajustes_serie_id_numero")
                        .HasFilter("numero IS NOT NULL");

                    b.ToTable("ajustes", "inventario");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Ajustes.LineaDeAjuste", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AjusteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ajuste_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal>("CantidadIntroducida")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad_introducida")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal>("FactorAUnidadBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("factor_a_unidad_base")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<Guid>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UnidadIntroducidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_introducida_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CosteUnitario", "Bastion.Inventario.Domain.Ajustes.LineaDeAjuste.CosteUnitario#Importe", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Cantidad")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("coste_unitario_cantidad")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");

                            b1.Property<string>("Divisa")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("coste_unitario_divisa")
                                .HasAnnotation("Bastion:Auditoria", "Auditada|");
                        });

                    b.HasKey("Id")
                        .HasName("pk_lineas_ajuste");

                    b.HasIndex("AjusteId")
                        .HasDatabaseName("ix_lineas_ajuste_ajuste_id");

                    b.ToTable("lineas_ajuste", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_lineas_ajuste_cantidad_y_factor", "cantidad_introducida <> 0 AND factor_a_unidad_base > 0");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Movimientos.MovimientoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("FechaDeOperacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_operacion");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<decimal>("CantidadEnUnidadBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad_en_unidad_base");

                    b.Property<decimal>("CantidadIntroducida")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad_introducida");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<Guid>("DocumentoOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_origen_id");

                    b.Property<string>("DocumentoOrigenTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento_origen_tipo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("FactorAUnidadBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("factor_a_unidad_base");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<Guid>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id");

                    b.Property<Guid>("UnidadIntroducidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_introducida_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "CosteUnitario", "Bastion.Inventario.Domain.Movimientos.MovimientoStock.CosteUnitario#Importe", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Cantidad")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("coste_unitario_cantidad");

                            b1.Property<string>("Divisa")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("coste_unitario_divisa");
                        });

                    b.HasKey("Id", "FechaDeOperacion")
                        .HasName("pk_movimiento_stock");

                    b.HasIndex("DocumentoOrigenTipo", "DocumentoOrigenId")
                        .HasDatabaseName("ix_movimiento_stock_documento_origen_tipo_documento_origen_id");

                    b.HasIndex("EmpresaId", "ArticuloId", "UbicacionId", "FechaDeOperacion")
                        .HasDatabaseName("ix_movimiento_stock_empresa_id_articulo_id_ubicacion_id_fecha_");

                    b.ToTable("movimiento_stock", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_movimiento_stock_cantidad_no_nula", "cantidad_introducida <> 0 AND cantidad_en_unidad_base <> 0");

                            t.HasCheckConstraint("ck_movimiento_stock_cantidad_por_factor", "cantidad_en_unidad_base = round(cantidad_introducida * factor_a_unidad_base, 6)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|por R2 no cambia nunca, y cada fila ya dice quién, cuándo, qué y contra qué documento: la traza de esta tabla registraría cero cambios y pesaría lo que la tabla");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Ajustes.LineaDeAjuste", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.Ajustes.Ajuste", null)
                        .WithMany("Lineas")
                        .HasForeignKey("AjusteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_ajuste_ajustes_ajuste_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Ajustes.Ajuste", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
