// <auto-generated />
using System;
using Bastion.Inventario.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bastion.Inventario.Infrastructure.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20261009150913_LasReservas")]
    partial class LasReservas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventario")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Auditoria.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cambio")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cambio");

                    b.Property<Guid>("CorrelacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlacion_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Valores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("valores");

                    b.HasKey("Id")
                        .HasName("pk_registros");

                    b.HasIndex("CorrelacionId")
                        .HasDatabaseName("ix_registros_correlacion_id");

                    b.HasIndex("OcurridoEn")
                        .HasDatabaseName("ix_registros_ocurrido_en");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_registros_entidad_entidad_id");

                    b.ToTable("registros", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_registros_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la traza; auditarla sería recursión, no información");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoDeLaBandeja", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cuerpo");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<DateTimeOffset?>("PublicadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id")
                        .HasName("pk_bandeja_de_salida");

                    b.HasIndex("EventoId")
                        .IsUnique()
                        .HasDatabaseName("ix_bandeja_evento_id");

                    b.HasIndex("Estado", "Id")
                        .HasDatabaseName("ix_bandeja_de_salida_estado_id");

                    b.ToTable("bandeja_de_salida", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_bandeja_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la cola de eventos; publicarlos es fontanería, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("Consumidor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("consumidor");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.HasKey("EventoId", "Consumidor")
                        .HasName("pk_eventos_procesados");

                    b.ToTable("eventos_procesados", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la huella de que un consumidor ya pasó; no es un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Idempotencia.RegistroDeIdempotencia", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Metodo")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("metodo");

                    b.Property<string>("Ruta")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ruta");

                    b.Property<string>("Clave")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CaducaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("caduca_en");

                    b.Property<int?>("CodigoDeEstado")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_de_estado");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("TipoDeContenido")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tipo_de_contenido");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ubicacion");

                    b.HasKey("EmpresaId", "UsuarioId", "Metodo", "Ruta", "Clave")
                        .HasName("pk_claves_de_idempotencia");

                    b.HasIndex("CaducaEn")
                        .HasDatabaseName("ix_claves_de_idempotencia_caduca_en");

                    b.ToTable("claves_de_idempotencia", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es el recibo de una petición ya atendida, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Ajustes.Ajuste", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid?>("AnulaAId")
                        .HasColumnType("uuid")
                        .HasColumnName("anula_a_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("divisa")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("FechaDeOperacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_operacion")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<long?>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid?>("RecuentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recuento_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid")
                        .HasColumnName("serie_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_ajustes");

                    b.HasIndex("AnulaAId")
                        .IsUnique()
                        .HasDatabaseName("ix_ajustes_anula_a_id")
                        .HasFilter("anula_a_id IS NOT NULL");

                    b.HasIndex("RecuentoId")
                        .IsUnique()
                        .HasDatabaseName("ix_ajustes_recuento_id")
                        .HasFilter("recuento_id IS NOT NULL");

                    b.HasIndex("EmpresaId", "FechaDeOperacion")
                        .HasDatabaseName("ix_ajustes_empresa_id_fecha_de_operacion");

                    b.HasIndex("SerieId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_ajustes_serie_id_numero")
                        .HasFilter("numero IS NOT NULL");

                    b.ToTable("ajustes", "inventario");

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Ajustes.LineaDeAjuste", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AjusteId")
                        .HasColumnType("uuid")
                        .HasColumnName("ajuste_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal>("CantidadIntroducida")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad_introducida")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("CodigoDeLote")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_de_lote")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal?>("CosteUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("coste_unitario")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal>("FactorAUnidadBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("factor_a_unidad_base")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("NumeroDeSerie")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_de_serie")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UnidadIntroducidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_introducida_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal?>("ValorQueCompensa")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_que_compensa")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.HasKey("Id")
                        .HasName("pk_lineas_ajuste");

                    b.HasIndex("AjusteId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_lineas_ajuste_ajuste_id_numero");

                    b.ToTable("lineas_ajuste", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_lineas_ajuste_cantidad_y_factor", "cantidad_introducida <> 0 AND factor_a_unidad_base > 0");

                            t.HasCheckConstraint("ck_lineas_ajuste_numero_desde_uno", "numero > 0");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Existencias.CorteDeLaInstantanea", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<DateOnly>("HastaElMes")
                        .HasColumnType("date")
                        .HasColumnName("hasta_el_mes");

                    b.HasKey("EmpresaId")
                        .HasName("pk_cortes_de_la_instantanea");

                    b.ToTable("cortes_de_la_instantanea", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_cortes_de_la_instantanea_mes_es_primer_dia", "extract(day from hasta_el_mes) = 1");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|lo escribe en crudo el recálculo de las instantáneas, que no pasa por el rastreador, y solo dice hasta dónde llega una copia que se puede tirar");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Existencias.Existencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("EnTransito")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("en_transito");

                    b.Property<decimal>("Fisico")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("fisico");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<Guid?>("NumeroDeSerieId")
                        .HasColumnType("uuid")
                        .HasColumnName("numero_de_serie_id");

                    b.Property<Guid>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id");

                    b.HasKey("Id")
                        .HasName("pk_existencias");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_existencias_lote_id");

                    b.HasIndex("NumeroDeSerieId")
                        .HasDatabaseName("ix_existencias_numero_de_serie_id");

                    b.HasIndex("EmpresaId", "ArticuloId", "NumeroDeSerieId")
                        .IsUnique()
                        .HasDatabaseName("ix_existencias_numero_de_serie_en_un_sitio")
                        .HasFilter("(fisico > 0 OR en_transito > 0) AND numero_de_serie_id IS NOT NULL");

                    b.HasIndex("EmpresaId", "ArticuloId", "AlmacenId", "UbicacionId", "LoteId", "NumeroDeSerieId")
                        .IsUnique()
                        .HasDatabaseName("ix_existencias_una_por_clave");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("EmpresaId", "ArticuloId", "AlmacenId", "UbicacionId", "LoteId", "NumeroDeSerieId"), false);

                    b.ToTable("existencias", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_existencias_en_transito_no_negativo", "en_transito >= 0");

                            t.HasCheckConstraint("ck_existencias_fisico_no_negativo", "fisico >= 0");

                            t.HasCheckConstraint("ck_existencias_lote_o_numero_de_serie", "num_nonnulls(lote_id, numero_de_serie_id) <= 1");

                            t.HasCheckConstraint("ck_existencias_numero_de_serie_como_mucho_una", "numero_de_serie_id IS NULL OR fisico + en_transito <= 1");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|la mueve en crudo la sentencia que anota el libro, que no pasa por el rastreador de cambios, y cada cambio suyo es una fila del libro, que ya es su traza");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Existencias.InstantaneaMensual", b =>
                {
                    b.Property<Guid>("ExistenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("existencia_id");

                    b.Property<DateOnly>("Mes")
                        .HasColumnType("date")
                        .HasColumnName("mes");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("Fisico")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("fisico");

                    b.HasKey("ExistenciaId", "Mes")
                        .HasName("pk_instantaneas_mensuales");

                    b.HasIndex("EmpresaId")
                        .HasDatabaseName("ix_instantaneas_mensuales_empresa_id");

                    b.ToTable("instantaneas_mensuales", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_instantaneas_mensuales_mes_es_primer_dia", "extract(day from mes) = 1");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es una optimización que se puede borrar y recalcular desde el libro, y la escriben en crudo la sentencia que anota el libro y el recálculo, que no pasan por el rastreador");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.LotesYSeries.Lote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.HasKey("Id")
                        .HasName("pk_lotes");

                    b.HasIndex("EmpresaId", "ArticuloId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_lotes_empresa_id_articulo_id_codigo");

                    b.ToTable("lotes", "inventario");

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|la crea en crudo la sentencia que resuelve los códigos, que no pasa por el rastreador de cambios, y no cambia nunca: cuándo entró y de quién lo dice el libro, que la apunta");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.LotesYSeries.NumeroDeSerie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero");

                    b.HasKey("Id")
                        .HasName("pk_numeros_de_serie");

                    b.HasIndex("EmpresaId", "ArticuloId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_numeros_de_serie_empresa_id_articulo_id_numero");

                    b.ToTable("numeros_de_serie", "inventario");

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|la crea en crudo la sentencia que resuelve los códigos, que no pasa por el rastreador de cambios, y no cambia nunca: dónde estuvo la unidad lo dice el libro, que la apunta");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Movimientos.MovimientoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("FechaDeOperacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_operacion");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<decimal>("CantidadEnUnidadBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad_en_unidad_base");

                    b.Property<decimal>("CantidadIntroducida")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad_introducida");

                    b.Property<decimal?>("CosteUnitarioSinDivisa")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("coste_unitario");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("divisa");

                    b.Property<Guid>("DocumentoOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_origen_id");

                    b.Property<string>("DocumentoOrigenTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento_origen_tipo");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<decimal>("FactorAUnidadBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("factor_a_unidad_base");

                    b.Property<Guid?>("LoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("lote_id");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en");

                    b.Property<Guid?>("NumeroDeSerieId")
                        .HasColumnType("uuid")
                        .HasColumnName("numero_de_serie_id");

                    b.Property<decimal>("PrecioMedioSinDivisa")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("precio_medio");

                    b.Property<Guid>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id");

                    b.Property<Guid>("UnidadIntroducidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_introducida_id");

                    b.Property<decimal>("ValorSinDivisa")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor");

                    b.HasKey("Id", "FechaDeOperacion")
                        .HasName("pk_movimiento_stock");

                    b.HasIndex("LoteId")
                        .HasDatabaseName("ix_movimiento_stock_lote_id");

                    b.HasIndex("NumeroDeSerieId")
                        .HasDatabaseName("ix_movimiento_stock_numero_de_serie_id");

                    b.HasIndex("DocumentoOrigenTipo", "DocumentoOrigenId")
                        .HasDatabaseName("ix_movimiento_stock_documento_origen_tipo_documento_origen_id");

                    b.HasIndex("EmpresaId", "ArticuloId", "UbicacionId", "FechaDeOperacion")
                        .HasDatabaseName("ix_movimiento_stock_empresa_id_articulo_id_ubicacion_id_fecha_");

                    b.ToTable("movimiento_stock", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_movimiento_stock_cantidad_no_nula", "cantidad_introducida <> 0 AND cantidad_en_unidad_base <> 0");

                            t.HasCheckConstraint("ck_movimiento_stock_cantidad_por_factor", "cantidad_en_unidad_base = round(cantidad_introducida * factor_a_unidad_base, 6)");

                            t.HasCheckConstraint("ck_movimiento_stock_lote_o_numero_de_serie", "num_nonnulls(lote_id, numero_de_serie_id) <= 1");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|por R2 no cambia nunca, y cada fila ya dice quién, cuándo, qué y contra qué documento: la traza de esta tabla registraría cero cambios y pesaría lo que la tabla");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Recuentos.LineaDeRecuento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("CodigoDeLote")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_de_lote")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal?>("Contado")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("contado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal?>("CosteUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("coste_unitario")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid?>("LineaDeAjusteId")
                        .HasColumnType("uuid")
                        .HasColumnName("linea_de_ajuste_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("NumeroDeSerie")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_de_serie")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("RecuentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recuento_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal?>("TeoricoAlContar")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("teorico_al_contar")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UbicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UnidadBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_base_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_lineas_recuento");

                    b.HasIndex("LineaDeAjusteId")
                        .IsUnique()
                        .HasDatabaseName("ix_lineas_recuento_linea_de_ajuste_id")
                        .HasFilter("linea_de_ajuste_id IS NOT NULL");

                    b.HasIndex("RecuentoId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_lineas_recuento_recuento_id_numero");

                    b.HasIndex("RecuentoId", "ArticuloId", "NumeroDeSerie")
                        .IsUnique()
                        .HasDatabaseName("ix_lineas_recuento_una_por_serie")
                        .HasFilter("numero_de_serie IS NOT NULL");

                    b.HasIndex("RecuentoId", "ArticuloId", "UbicacionId", "CodigoDeLote", "NumeroDeSerie")
                        .IsUnique()
                        .HasDatabaseName("ix_lineas_recuento_una_por_clave");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("RecuentoId", "ArticuloId", "UbicacionId", "CodigoDeLote", "NumeroDeSerie"), false);

                    b.ToTable("lineas_recuento", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_lineas_recuento_contado_con_su_teorico", "(contado IS NULL) = (teorico_al_contar IS NULL)");

                            t.HasCheckConstraint("ck_lineas_recuento_contado_no_negativo", "contado IS NULL OR contado >= 0");

                            t.HasCheckConstraint("ck_lineas_recuento_coste_solo_al_anadir", "coste_unitario IS NULL OR (origen = 'Anadida' AND coste_unitario >= 0)");

                            t.HasCheckConstraint("ck_lineas_recuento_lote_o_serie", "codigo_de_lote IS NULL OR numero_de_serie IS NULL");

                            t.HasCheckConstraint("ck_lineas_recuento_numero_desde_uno", "numero > 0");

                            t.HasCheckConstraint("ck_lineas_recuento_serie_en_cero_o_uno", "numero_de_serie IS NULL OR contado IS NULL OR contado IN (0, 1)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Recuentos.Recuento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("divisa")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("FechaDeApertura")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_apertura")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly?>("FechaDeConfirmacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_confirmacion")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("MotivoDeLaAnulacion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_de_la_anulacion")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("MotivoDelDescarte")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo_del_descarte")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<long?>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("SerieDelAjusteId")
                        .HasColumnType("uuid")
                        .HasColumnName("serie_del_ajuste_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid")
                        .HasColumnName("serie_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_recuentos");

                    b.HasIndex("EmpresaId", "AlmacenId")
                        .IsUnique()
                        .HasDatabaseName("ix_recuentos_uno_en_curso_por_almacen")
                        .HasFilter("estado = 'EnCurso'");

                    b.HasIndex("EmpresaId", "FechaDeConfirmacion")
                        .HasDatabaseName("ix_recuentos_empresa_id_fecha_de_confirmacion");

                    b.HasIndex("SerieId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_recuentos_serie_id_numero")
                        .HasFilter("numero IS NOT NULL");

                    b.ToTable("recuentos", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_recuentos_confirmacion_no_antes_de_la_apertura", "fecha_de_confirmacion IS NULL OR fecha_de_confirmacion >= fecha_de_apertura");

                            t.HasCheckConstraint("ck_recuentos_numerado_si_se_confirmo", "(numero IS NOT NULL AND fecha_de_confirmacion IS NOT NULL) = (estado IN ('Confirmado', 'Anulado'))");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Reservas.ConsumoDeReserva", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("DocumentoTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento_tipo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("FechaDeOperacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_operacion")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<Guid>("ReservaId")
                        .HasColumnType("uuid")
                        .HasColumnName("reserva_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.HasKey("Id")
                        .HasName("pk_consumos_de_reserva");

                    b.HasIndex("DocumentoTipo", "DocumentoId")
                        .HasDatabaseName("ix_consumos_de_reserva_documento_tipo_documento_id");

                    b.HasIndex("ReservaId", "DocumentoTipo", "DocumentoId")
                        .IsUnique()
                        .HasDatabaseName("ix_consumos_de_reserva_uno_por_documento");

                    b.ToTable("consumos_de_reserva", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_consumos_de_reserva_cantidad_positiva", "cantidad > 0");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Reservas.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset?>("CaducaEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("caduca_el")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Causa")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("causa")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset?>("LiberadaEl")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("liberada_el")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("OrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("origen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<int>("OrigenLinea")
                        .HasColumnType("integer")
                        .HasColumnName("origen_linea")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("OrigenTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origen_tipo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UnidadBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_base_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_reservas");

                    b.HasIndex("EmpresaId", "ArticuloId", "AlmacenId")
                        .HasDatabaseName("ix_reservas_activas_por_clave")
                        .HasFilter("estado = 'Activa'");

                    b.HasIndex("EmpresaId", "OrigenTipo", "OrigenId", "OrigenLinea")
                        .IsUnique()
                        .HasDatabaseName("ix_reservas_una_por_origen");

                    b.ToTable("reservas", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_reservas_caducidad_en_su_fecha", "causa IS DISTINCT FROM 'Caducidad' OR COALESCE(liberada_el = caduca_el, FALSE)");

                            t.HasCheckConstraint("ck_reservas_cantidad_positiva", "cantidad > 0");

                            t.HasCheckConstraint("ck_reservas_liberada_con_causa_y_fecha", "(estado = 'Liberada') = (causa IS NOT NULL) AND (estado = 'Liberada') = (liberada_el IS NOT NULL)");

                            t.HasCheckConstraint("ck_reservas_motivo_solo_a_mano", "(motivo IS NOT NULL) = COALESCE(causa = 'AMano', FALSE)");

                            t.HasCheckConstraint("ck_reservas_origen_linea_desde_uno", "origen_linea > 0");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Transferencias.LineaDeTransferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal>("CantidadIntroducida")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad_introducida")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("CodigoDeLote")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_de_lote")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal>("FactorAUnidadBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("factor_a_unidad_base")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("NumeroDeSerie")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_de_serie")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("TransferenciaId")
                        .HasColumnType("uuid")
                        .HasColumnName("transferencia_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UbicacionDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_destino_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UbicacionOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("ubicacion_origen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UnidadIntroducidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_introducida_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<decimal?>("ValorQueCompensa")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_que_compensa")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.HasKey("Id")
                        .HasName("pk_lineas_transferencia");

                    b.HasIndex("TransferenciaId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_lineas_transferencia_transferencia_id_numero");

                    b.ToTable("lineas_transferencia", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_lineas_transferencia_cantidad_y_factor", "cantidad_introducida <> 0 AND factor_a_unidad_base > 0");

                            t.HasCheckConstraint("ck_lineas_transferencia_numero_desde_uno", "numero > 0");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Transferencias.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlmacenDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_destino_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("AlmacenOrigenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_origen_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid?>("AnulaAId")
                        .HasColumnType("uuid")
                        .HasColumnName("anula_a_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("divisa")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly>("FechaDeEnvio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_envio")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateOnly?>("FechaDeRecepcion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_de_recepcion")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("motivo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<long?>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("SerieId")
                        .HasColumnType("uuid")
                        .HasColumnName("serie_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_transferencias");

                    b.HasIndex("AnulaAId")
                        .IsUnique()
                        .HasDatabaseName("ix_transferencias_anula_a_id")
                        .HasFilter("anula_a_id IS NOT NULL");

                    b.HasIndex("EmpresaId", "FechaDeEnvio")
                        .HasDatabaseName("ix_transferencias_empresa_id_fecha_de_envio");

                    b.HasIndex("EmpresaId", "FechaDeRecepcion")
                        .HasDatabaseName("ix_transferencias_empresa_id_fecha_de_recepcion");

                    b.HasIndex("SerieId", "Numero")
                        .IsUnique()
                        .HasDatabaseName("ix_transferencias_serie_id_numero")
                        .HasFilter("numero IS NOT NULL");

                    b.ToTable("transferencias", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_transferencias_origen_distinto_del_destino", "almacen_origen_id <> almacen_destino_id");

                            t.HasCheckConstraint("ck_transferencias_recepcion_no_antes_del_envio", "fecha_de_recepcion IS NULL OR fecha_de_recepcion >= fecha_de_envio");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Valoraciones.Valoracion", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("ArticuloId")
                        .HasColumnType("uuid")
                        .HasColumnName("articulo_id");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid")
                        .HasColumnName("almacen_id");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Divisa")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("divisa");

                    b.Property<decimal>("EnTransito")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("en_transito");

                    b.Property<DateOnly?>("UltimaFecha")
                        .HasColumnType("date")
                        .HasColumnName("ultima_fecha");

                    b.Property<decimal>("ValorEnTransitoSinDivisa")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor_en_transito");

                    b.Property<decimal>("ValorSinDivisa")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("valor");

                    b.HasKey("EmpresaId", "ArticuloId", "AlmacenId")
                        .HasName("pk_valoraciones");

                    b.ToTable("valoraciones", "inventario", t =>
                        {
                            t.HasCheckConstraint("ck_valoraciones_cantidad_no_negativa", "cantidad >= 0");

                            t.HasCheckConstraint("ck_valoraciones_en_transito_no_negativo", "en_transito >= 0");

                            t.HasCheckConstraint("ck_valoraciones_sin_cantidad_no_hay_valor", "cantidad > 0 OR valor = 0");

                            t.HasCheckConstraint("ck_valoraciones_sin_transito_no_hay_valor_en_transito", "en_transito > 0 OR valor_en_transito = 0");

                            t.HasCheckConstraint("ck_valoraciones_valor_en_transito_no_negativo", "valor_en_transito >= 0");

                            t.HasCheckConstraint("ck_valoraciones_valor_no_negativo", "valor >= 0");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|la mueven en crudo las sentencias que anotan el libro, que no pasan por el rastreador de cambios, y cada cambio suyo es una fila del libro con su valor, que ya es su traza");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Ajustes.Ajuste", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.Ajustes.Ajuste", null)
                        .WithMany()
                        .HasForeignKey("AnulaAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ajustes_ajustes_anula_a_id");

                    b.HasOne("Bastion.Inventario.Domain.Recuentos.Recuento", null)
                        .WithMany()
                        .HasForeignKey("RecuentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ajustes_recuentos_recuento_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Ajustes.LineaDeAjuste", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.Ajustes.Ajuste", null)
                        .WithMany("Lineas")
                        .HasForeignKey("AjusteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_ajuste_ajustes_ajuste_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Existencias.Existencia", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.LotesYSeries.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_existencias_lotes_lote_id");

                    b.HasOne("Bastion.Inventario.Domain.LotesYSeries.NumeroDeSerie", null)
                        .WithMany()
                        .HasForeignKey("NumeroDeSerieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_existencias_numeros_de_serie_numero_de_serie_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Existencias.InstantaneaMensual", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.Existencias.Existencia", null)
                        .WithMany()
                        .HasForeignKey("ExistenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instantaneas_mensuales_existencias_existencia_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Movimientos.MovimientoStock", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.LotesYSeries.Lote", null)
                        .WithMany()
                        .HasForeignKey("LoteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimiento_stock_lotes_lote_id");

                    b.HasOne("Bastion.Inventario.Domain.LotesYSeries.NumeroDeSerie", null)
                        .WithMany()
                        .HasForeignKey("NumeroDeSerieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_movimiento_stock_numeros_de_serie_numero_de_serie_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Recuentos.LineaDeRecuento", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.Ajustes.LineaDeAjuste", null)
                        .WithMany()
                        .HasForeignKey("LineaDeAjusteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_lineas_recuento_lineas_ajuste_linea_de_ajuste_id");

                    b.HasOne("Bastion.Inventario.Domain.Recuentos.Recuento", null)
                        .WithMany("Lineas")
                        .HasForeignKey("RecuentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_recuento_recuentos_recuento_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Reservas.ConsumoDeReserva", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.Reservas.Reserva", null)
                        .WithMany("Consumos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consumos_de_reserva_reservas_reserva_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Transferencias.LineaDeTransferencia", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.Transferencias.Transferencia", null)
                        .WithMany("Lineas")
                        .HasForeignKey("TransferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineas_transferencia_transferencias_transferencia_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Transferencias.Transferencia", b =>
                {
                    b.HasOne("Bastion.Inventario.Domain.Transferencias.Transferencia", null)
                        .WithMany()
                        .HasForeignKey("AnulaAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transferencias_transferencias_anula_a_id");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Ajustes.Ajuste", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Recuentos.Recuento", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Reservas.Reserva", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("Bastion.Inventario.Domain.Transferencias.Transferencia", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
