// <auto-generated />
using System;
using Bastion.Catalogo.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bastion.Catalogo.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogoDbContext))]
    [Migration("20260908062337_EsquemaInicialDeCatalogo")]
    partial class EsquemaInicialDeCatalogo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalogo")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Auditoria.RegistroDeAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cambio")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cambio");

                    b.Property<Guid>("CorrelacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlacion_id");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("entidad");

                    b.Property<string>("EntidadId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("entidad_id");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Valores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("valores");

                    b.HasKey("Id")
                        .HasName("pk_registros");

                    b.HasIndex("CorrelacionId")
                        .HasDatabaseName("ix_registros_correlacion_id");

                    b.HasIndex("OcurridoEn")
                        .HasDatabaseName("ix_registros_ocurrido_en");

                    b.HasIndex("Entidad", "EntidadId")
                        .HasDatabaseName("ix_registros_entidad_entidad_id");

                    b.ToTable("registros", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_registros_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la traza; auditarla sería recursión, no información");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoDeLaBandeja", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cuerpo");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("estado");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<int>("Intentos")
                        .HasColumnType("integer")
                        .HasColumnName("intentos");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nombre");

                    b.Property<DateTimeOffset>("OcurridoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocurrido_en");

                    b.Property<DateTimeOffset?>("PublicadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicado_en");

                    b.Property<string>("SinInquilino")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sin_inquilino");

                    b.Property<string>("UltimoError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("ultimo_error");

                    b.HasKey("Id")
                        .HasName("pk_bandeja_de_salida");

                    b.HasIndex("EventoId")
                        .IsUnique()
                        .HasDatabaseName("ix_bandeja_evento_id");

                    b.HasIndex("Estado", "Id")
                        .HasDatabaseName("ix_bandeja_de_salida_estado_id");

                    b.ToTable("bandeja_de_salida", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();

                            t.HasCheckConstraint("ck_bandeja_empresa_o_motivo", "(empresa_id IS NULL) <> (sin_inquilino IS NULL)");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la cola de eventos; publicarlos es fontanería, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.BandejaDeSalida.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<string>("Consumidor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("consumidor");

                    b.Property<DateTimeOffset>("ProcesadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("procesado_en");

                    b.HasKey("EventoId", "Consumidor")
                        .HasName("pk_eventos_procesados");

                    b.ToTable("eventos_procesados", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es la huella de que un consumidor ya pasó; no es un cambio de datos");
                });

            modelBuilder.Entity("Bastion.BuildingBlocks.Infrastructure.Idempotencia.RegistroDeIdempotencia", b =>
                {
                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Metodo")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("metodo");

                    b.Property<string>("Ruta")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ruta");

                    b.Property<string>("Clave")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("clave");

                    b.Property<int?>("CodigoDeEstado")
                        .HasColumnType("integer")
                        .HasColumnName("codigo_de_estado");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creada_en");

                    b.Property<string>("Cuerpo")
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<string>("Etiqueta")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("etiqueta");

                    b.Property<string>("Huella")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("TipoDeContenido")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tipo_de_contenido");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("ubicacion");

                    b.HasKey("EmpresaId", "UsuarioId", "Metodo", "Ruta", "Clave")
                        .HasName("pk_claves_de_idempotencia");

                    b.ToTable("claves_de_idempotencia", "auditoria", t =>
                        {
                            t.ExcludeFromMigrations();
                        });

                    b.HasAnnotation("Bastion:Auditoria", "NoAuditada|es el recibo de una petición ya atendida, no un cambio de datos");
                });

            modelBuilder.Entity("Bastion.Catalogo.Domain.Catalogo.Articulo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("ImpuestoPorDefectoId")
                        .HasColumnType("uuid")
                        .HasColumnName("impuesto_por_defecto_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("UnidadBaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("unidad_base_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_articulos");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_articulos_categoria_id");

                    b.HasIndex("EmpresaId", "CategoriaId")
                        .HasDatabaseName("ix_articulos_empresa_id_categoria_id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_articulos_empresa_id_codigo");

                    b.ToTable("articulos", "catalogo", t =>
                        {
                            t.HasCheckConstraint("ck_articulos_tipo", "tipo IN ('Bien', 'Servicio')");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Catalogo.Domain.Catalogo.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid")
                        .HasColumnName("empresa_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<DateTimeOffset>("ModificadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modificado_en")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|cambia en cada modificación y la traza ya lleva su propio `ocurrido_en`");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<Guid?>("PadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("padre_id")
                        .HasAnnotation("Bastion:Auditoria", "Auditada|");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin")
                        .HasAnnotation("Bastion:Auditoria", "NoAuditada|es el testigo de concurrencia (xmin): lo pone PostgreSQL en cada escritura y no es un dato del negocio. Auditar su cambio sería anotar que hubo un cambio en la misma fila que ya anota cuál fue.");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("PadreId")
                        .HasDatabaseName("ix_categorias_padre_id");

                    b.HasIndex("EmpresaId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_empresa_id_codigo");

                    b.HasIndex("EmpresaId", "PadreId")
                        .HasDatabaseName("ix_categorias_empresa_id_padre_id");

                    b.ToTable("categorias", "catalogo", t =>
                        {
                            t.HasCheckConstraint("ck_categorias_padre_distinto_de_si_misma", "padre_id IS NULL OR padre_id <> id");
                        });

                    b.HasAnnotation("Bastion:Auditoria", "Auditada|");
                });

            modelBuilder.Entity("Bastion.Catalogo.Domain.Catalogo.Articulo", b =>
                {
                    b.HasOne("Bastion.Catalogo.Domain.Catalogo.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_articulos_categorias_categoria_id");
                });

            modelBuilder.Entity("Bastion.Catalogo.Domain.Catalogo.Categoria", b =>
                {
                    b.HasOne("Bastion.Catalogo.Domain.Catalogo.Categoria", null)
                        .WithMany()
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categorias_categorias_padre_id");
                });
#pragma warning restore 612, 618
        }
    }
}
